"""
Django settings for EcoCircular project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url  # Para parsear la URL de la base de datos de Railway
from dotenv import load_dotenv  # Para cargar variables locales

# Cargar variables desde un archivo .env si existe (solo desarrollo)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# --- SEGURIDAD ---
# En desarrollo usamos un valor por defecto, en producción DEBE estar en Railway
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-debug-key-123')

# DEBUG es True por defecto en local, pero False si RAILWAY_ENVIRONMENT existe
DEBUG = os.getenv('RAILWAY_ENVIRONMENT') is None

# Permitir todos los hosts en Railway, o definir específicamente
ALLOWED_HOSTS = ['*'] if not DEBUG else ['localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tesis.apps.TesisConfig',
    'django_recaptcha',
    'honeypot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EcoCircular.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Según tu estructura de imagen
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EcoCircular.wsgi.application'

# --- BASE DE DATOS (AUTOMATIZADA) ---
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Si estamos en Railway, usamos la configuración automática
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600)
    }
else:
    # Forzamos la configuración local para evitar el error de "clock" o "tesis"
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'tesis',  # Asegúrate de que este sea el nombre creado en tu Postgres local
            'USER': 'postgres',
            'PASSWORD': 'admin',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Havana'

USE_I18N = True
USE_L10N = True
USE_TZ = True

# --- CONFIGURACIÓN DE SEGURIDAD PARA PRODUCCIÓN ---
CSRF_TRUSTED_ORIGINS = [
    'https://tesis-production-b8b1.up.railway.app',
]

# --- ARCHIVOS ESTÁTICOS Y MEDIA ---
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

RECAPTCHA_V3_ACTION = 'registration'
RECAPTCHA_V3_THRESHOLD = 0.5
RECAPTCHA_PUBLIC_KEY = '6Le3oq4sAAAAADc8bwEaKHE1C31YV8kcw3q811aw'
RECAPTCHA_PRIVATE_KEY = '6Le3oq4sAAAAAIMH2cVhOdEAakxPp1oK3PsGlSo1'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

AUTH_USER_MODEL = 'tesis.CustomUser'

PASSWORD_RESET_TIMEOUT = 259200

# Reconocer el protocolo HTTPS a través del proxy.
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

IS_PRODUCTION = os.getenv('RAILWAY_ENVIRONMENT') is not None

if IS_PRODUCTION:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
    EMAIL_TIMEOUT = 10

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'testing@ecocircular.local'

    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
