# Generated by Django 6.0.3 on 2026-05-07 00:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.',
                                                     verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'},
                                              help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True,
                                              validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active',
                 models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                                     verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario con este correo electrónico.'}, max_length=255, unique=True,
                                            verbose_name='Correo Electrónico')),
                ('ci', models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CI must be 11 digits')],
                                        verbose_name='Carnet de Identidad')),
                ('phone_number', models.CharField(max_length=8, null=True, unique=True,
                                                  validators=[django.core.validators.RegexValidator(message='El número debe ser un móvil (5...).', regex='^5\\d{7}$')],
                                                  verbose_name='Teléfono')),
                ('location', models.CharField(max_length=75, verbose_name='Dirección')),
                ('entity_type', models.CharField(choices=[('tcp', 'Trabajador por Cuenta Propia'), ('organization', 'Organización/Empresa')], max_length=15,
                                                 verbose_name='Tipo de Entidad')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('groups',
                 models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                        related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions',
                 models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user',
                                        to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'permissions': [('can_change_admin_data', 'Puede editar campos de administrador'), ('can_change_other_data', 'Puede editar datos de otros usuarios')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuario (Histórico)')),
                ('event_type', models.CharField(
                    choices=[('AUTH:REGISTRO', 'Creación de cuenta'), ('AUTH:INICIO', 'Inicio de sesión'), ('AUTH:INICIO_ERROR', 'Error de inicio de sesión'),
                             ('AUTH:CIERRE', 'Cierre de sesión'), ('VER:VERIFICACION_ENVIADA', 'Envío de verificación'), ('VER:VERIFICACION', 'Verificación exitosa'),
                             ('VER:VERIFICACION_REMOVIDA', 'Verificación removida'), ('VER:VERIFICAION_ERR', 'Error de verificación'),
                             ('SEC:CONTRASEÑA_CAMBIO', 'Cambio de contraseña'), ('SEC:CORREO_CAMBIO', 'Cambio de correo'),
                             ('SEC:ACTIVIDAD_INUSUAL', 'Actividad inusual')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos de Seguridad')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('proxy_info', models.CharField(blank=True, help_text='HTTP_VIA / Forwarded headers', max_length=255, null=True)),
                ('accept_language', models.CharField(blank=True, max_length=50, null=True)),
                ('session_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Autenticación',
                'verbose_name_plural': 'Logs de Autenticación',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='tesis_logs_user_id_859428_idx')],
            },
        ),
    ]
