# Generated by Django 6.0.3 on 2026-04-17 15:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.',
                                                     verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('ci', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El CI debe contener exactamente 11 dígitos.')],
                                        verbose_name='Carnet de Identidad')),
                ('location', models.CharField(
                    choices=[('arroyo_naranjo', 'Arroyo Naranjo'), ('boyeros', 'Boyeros'), ('centro_habana', 'Centro Habana'), ('cerro', 'Cerro'), ('cotorro', 'Cotorro'),
                             ('diez_de_octubre', 'Diez de Octubre'), ('guanabacoa', 'Guanabacoa'), ('habana_del_este', 'Habana del Este'),
                             ('habana_vieja', 'Habana Vieja'), ('la_lisa', 'La Lisa'), ('marianao', 'Marianao'), ('playa', 'Playa'),
                             ('plaza_revolucion', 'Plaza de la Revolución'), ('regla', 'Regla'), ('san_miguel_padron', 'San Miguel del Padrón')], default='---',
                    max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, validators=[
                    django.core.validators.RegexValidator(message='El número debe ser un móvil (+53 5...) o un fijo válido de La Habana (+53 7...).',
                                                          regex='^(\\+53)?(5[0-8]\\d{6}|7(20|26|27|83|86|87|76|79|64|62)\\d{5})$')], verbose_name='Teléfono (Cuba)')),
                ('is_active', models.BooleanField(default=False)),
                ('account_status',
                 models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('blocked', 'Bloqueada'), ('banned', 'Eliminada')], default='blocked',
                                  max_length=10)),
                ('account_verified', models.BooleanField(default=False)),
                ('roles', models.CharField(choices=[('user', 'Usuario'), ('admin', 'Administrador')], default='user', max_length=10)),
                ('entity_type',
                 models.CharField(choices=[('tcp', 'Trabajador por Cuenta Propia'), ('organization', 'Organización/Empresa')], default='---', max_length=15,
                                  verbose_name='Tipo de Entidad')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último inicio de sesión')),
                ('groups',
                 models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                        related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions',
                 models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user',
                                        to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='AuthLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuario (Histórico)')),
                ('event_type', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('account_creation', 'Creación de cuenta'),
                                                         ('verification', 'Verificación de cuenta')], max_length=20)),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalles del Evento')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Autenticación',
                'verbose_name_plural': 'Logs de Autenticación',
                'ordering': ['-timestamp'],
            },
        ),
    ]
