# Generated by Django 6.0.3 on 2026-04-21 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ci',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True,
                                   validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El CI debe contener exactamente 11 dígitos.')],
                                   verbose_name='Carnet de Identidad'),
        ),
    ]
